version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/cms'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/cms'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
