name: '[CLIENT] - On Pull Request'

on:
  pull_request:
    branches: [main]
    paths:
      - apps/client/**

jobs:
  lockfile:
    name: Update lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.11.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies (and update lock-file)
        run: pnpm install --frozen-lockfile=false

      - name: Check changed files
        uses: tj-actions/verify-changed-files@v12.0
        id: verify-changed-files
        with:
          files: |
            apps/client

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update lockfile" -a || true

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
