name: '[CMS] - On Pull Request'

on:
  pull_request:
    branches: [main]
    paths:
      - apps/cms/**

jobs:
  docker:
    name: Build CMS docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/cms/Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: false
