name: '[CMS] - Main'

on:
  push:
    branches: [main]
    paths:
      - apps/cms/**

jobs:
  lockfile:
    name: Update lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.11.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies (and update lock-file)
        run: pnpm install --frozen-lockfile=false

      - name: Check changed files
        uses: tj-actions/verify-changed-files@v12.0
        id: verify-changed-files
        with:
          files: |
            apps/cms

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update lockfile" -a || true

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  docker:
    name: Build and publish CMS docker image
    runs-on: ubuntu-latest
    needs: lockfile
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zareix
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: apps/cms
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/zareix/strapi:latest
