name: '[CMS] - Main'

on:
  push:
    branches: [main]
    paths:
      - apps/cms/**

jobs:
  docker:
    name: Build and publish CMS docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zareix
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/cms/Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: |
            ghcr.io/zareix/strapi:latest
