name: Docker images CI

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  docker:
    name: Build and publish CMS docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zareix
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cms
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/zareix/strapi:latest
