name: '[PROD] Build & Publish'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: 'Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run build command
        run: bun run build
      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          name: build-output-prod
          path: dist

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: 'Publish'
    needs: build
    outputs:
      published_url: ${{ steps.publish.outputs.deployment-url }}
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output-prod
          path: build-output
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          command: pages deploy --project-name=raphael-catarino-website --branch=main build-output
        id: publish
      - name: Outputs
        run: |
          echo "URL: ${{ steps.publish.outputs.deployment-url }}"

  unlightouse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: 'Unlighthouse'
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install -g @unlighthouse/cli puppeteer
      - name: Unlighthouse assertions and client
        run: unlighthouse-ci
      - name: Archive unlighthouse
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse
          path: unlighthouse
      - name: Publish results to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          command: pages deploy --project-name=raphael-catarino-website-unlighthouse --branch=main unlighthouse
