name: '[PREVIEW] Build & Publish'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: 'Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run build command
        run: |
          export NODE_ENV=production
          bun run build
      - name: Archive dist
        uses: actions/upload-artifact@v3
        with:
          name: build-output-preview
          path: dist

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: 'Publish'
    needs: build
    outputs:
      published_url: ${{ steps.publish.outputs.url }}
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output-preview
          path: build-output
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: raphael-catarino-website
          directory: build-output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          wranglerVersion: 3
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"
