name: '[PROD] Build & Publish'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: 'Build'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      - name: Install dependencies
        run: bun install
      - name: Save dependencies cache
        uses: actions/cache/save@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      - name: Run build command
        run: |
          export NODE_ENV=production
          bun run build
      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          name: build-output-prod
          path: dist

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: 'Publish'
    needs: build
    outputs:
      published_url: ${{ steps.publish.outputs.url }}
    steps:
      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output-prod
          path: build-output
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: raphael-catarino-website
          directory: build-output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"

  unlightouse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: 'Unlighthouse'
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install -g @unlighthouse/cli puppeteer
      - name: Unlighthouse assertions and client
        run: unlighthouse-ci
      - name: Archive unlighthouse
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse
          path: unlighthouse
      - name: Publish results to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: raphael-catarino-website-unlighthouse
          directory: unlighthouse
          branch: main
